export const dataVue = {
    API_KEY: '4cf3f07b09324b46a99f7028b6758a4e',
    localTime: null, 
    infoTexts: false,
    loading: true,
    iconId: null,
    city: null,
    country: null,
    mainTemp: null,
    maxTemp: null,
    minTemp: null,
    feelsLikeTemp: null,
    degreeSymbol: '℃',
    condition: null,
    clouds: '',
    uvi: '',
    humidity: '',
    pressure: '',
    visibility: '',
    dewPoint: '',
    aqi: '',
    slp: '',
    bgImage: 'foggy-n',
    detailDataTexts: true,
}